### ISSUE TITLE
不支持行内数学公式额

### ISSUE THREAD

**Issue by Smith-Cruise** [drmingdrmer/md2zhihu#15]
比如我 $\sqrt{123}$ 这种语法，无法正常转换。

**Comment by drmingdrmer** [comment]
inline math和block math都用`$$`. 起始`$$` 在一行内就是inline了.

例如测试里的:
https://github.com/drmingdrmer/md2zhihu/blob/624606256e353bf7039a6c2060e5983c8cc7faa7/test/data/zhihu/src/simple.md?plain=1#L172-L173
```
    要找到一个更好的偶节点的 quorum 集合, 一个方法是可以把偶数节点的集群看做是一个奇数节点集群加上一个节点x:
    $$ D = C \cup \{x\} $$
```

https://github.com/drmingdrmer/md2zhihu/blob/624606256e353bf7039a6c2060e5983c8cc7faa7/test/data/zhihu/want/simple.md?plain=1#L168-L169
```
    要找到一个更好的偶节点的 quorum 集合, 一个方法是可以把偶数节点的集群看做是一个奇数节点集群加上一个节点x:
    <img src="https://www.zhihu.com/equation?tex=%20D%20%3D%20C%20%5Ccup%20%5C%7Bx%5C%7D%20" alt=" D = C \cup \{x\} " class="ee_img tr_noresize" eeimg="1">
```

**Comment by Smith-Cruise** [comment]
能提供切换开关吗，很多的 markdown 行内数学公式语法是单个 $ 的。

**Comment by drmingdrmer** [comment]
hm...应该可以

**Comment by Smith-Cruise** [comment]
感谢，就等着你这个发文章了

**Comment by drmingdrmer** [comment]
https://github.com/marketplace/actions/md2zhihu
v0.12 版支持了`$` 作为math的标记, 是否inline根据上下文是否inline判断的, 不根据符号判断:

```
inline math: $ x $ 哈哈

inline math: $$
y
$$

inline math: $
y
$

block math:

$$
z
$$
```

```

inline math: <img src="https://www.zhihu.com/equation?tex=%20x%20" alt=" x " class="ee_img tr_noresize" eeimg="1"> 哈哈

inline math: <img src="https://www.zhihu.com/equation?tex=y" alt="y" class="ee_img tr_noresize" eeimg="1">

inline math: <img src="https://www.zhihu.com/equation?tex=y" alt="y" class="ee_img tr_noresize" eeimg="1">

block math:

<img src="https://www.zhihu.com/equation?tex=z%5C%5C" alt="z\\" class="ee_img tr_noresize" eeimg="1">
```

https://github.com/drmingdrmer/md2zhihu/blob/main/test/data/zhihu-math-inline/src/simple.md?plain=1
https://github.com/drmingdrmer/md2zhihu/blob/main/test/data/zhihu-math-inline/want/simple.md?plain=1
