### ISSUE TITLE
提一些微小 BUG

### ISSUE THREAD

**Issue by Smith-Cruise** [drmingdrmer/md2zhihu#22]
我的 markdown 采用 Typora 编写。

引用会多出一行：
<img width="894" alt="image" src="https://user-images.githubusercontent.com/18729228/152668270-851931b5-caff-4231-a317-3387bc7b1a50.png">

图片也会上下多出一行：
<img width="987" alt="image" src="https://user-images.githubusercontent.com/18729228/152668282-53c29706-a93e-470f-bd2c-1a8b8d1a0588.png">

部分表格不输出：
<img width="864" alt="image" src="https://user-images.githubusercontent.com/18729228/152668290-b5a90eb6-0174-4fa6-8b4c-69ccb48daee3.png">

需要测试的话我可以把源文件发你邮箱。

**Comment by drmingdrmer** [comment]
Ok. drdr.xp@gmail.com
以及你使用的版本和转换时的参数:DDD

**Comment by drmingdrmer** [comment]
我的github id 也是微信...要不这样方便点...

**Comment by drmingdrmer** [comment]
增加空行的问题是知乎编辑器导入时的bug, 生成的markdown没有问题. 这个问题只能让zhihu来解决了.

Table变空是因为知乎不认table标签里的colgroup(太宽的table会生成这个标签), md2zhihu里把这个标签去掉了. 宽table的问题在最新版 0.14 里不会出现了: https://github.com/marketplace/actions/md2zhihu


![image](https://user-images.githubusercontent.com/44069/153717394-a36d012c-c1e5-440d-911d-833c536a5ecc.png)

**Comment by Smith-Cruise** [comment]
thks
