### ISSUE TITLE
Github action failed, got error  `No such file or directory: 'mmdc'`

### ISSUE THREAD

**Issue by noneback** [drmingdrmer/md2zhihu#28]
I am trying to use action. But got error:

```python
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/blog/blog/md2zhihu/__main__.py", line 6, in <module>
    main()
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 1548, in main
    convert_md(conf)
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 1372, in convert_md
    output_lines = article.render()
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 1328, in render
    output_lines = mdr.render(self.ast)
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 392, in render
    rst.extend(self.render_node(n, ctx))
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 253, in render_node
    lines = self.handlers(self, n, ctx=ctx)
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 161, in zhihu_specific
    return render_with_features(mdrender, n, ctx=ctx, features=zhihu_features)
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 1099, in render_with_features
    return f[lang](mdrender, n, ctx=ctx)
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 85, in block_code_mermaid_to_jpg
    return typ_text_to_jpg(mdrender, 'mermaid', n['text'])
  File "/home/runner/work/blog/blog/md2zhihu/md2zhihu/__init__.py", line 93, in typ_text_to_jpg
    d = k3down2.convert(typ, txt, 'jpg', opt=opt)
  File "/home/runner/.local/lib/python3.8/site-packages/k3down2/down2.py", line 43, in convert
    inp = convert(input_typ, input, conv, opt=opt)
  File "/home/runner/.local/lib/python3.8/site-packages/k3down2/down2.py", line 40, in convert
    return conv(input, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/k3down2/down2.py", line 514, in mermaid_to_svg
    k3proc.command_ex(
  File "/home/runner/.local/lib/python3.8/site-packages/k3proc/proc.py", line 327, in command_ex
    return command(cmd, *arguments, **options)
  File "/home/runner/.local/lib/python3.8/site-packages/k3proc/proc.py", line 242, in command
    subproc = subprocess.Popen(cmds,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mmdc'
```
Here is my `.yml` and  `.github/workflows/md2zhihu.yml`
```yml
# .yml
- name: md2zhihu
  uses: drmingdrmer/md2zhihu@main


# md2zhihu.yml
name: md2zhihu
on: [push]
jobs:
  md2zhihu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: drmingdrmer/md2zhihu@main
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        pattern: >
            content/post/*.md
```
I have no idea how to fix it.

**Comment by drmingdrmer** [comment]
Is there a session url for this exception? I need to investigate the environment to figure out what's going on.
E.g. url like this:
https://github.com/drmingdrmer/drmingdrmer.github.io/runs/5168132554?check_suite_focus=true

`mmdc` is the `mermaid` binary executable. In the action definition file, it should be installed at line-50:
https://github.com/drmingdrmer/md2zhihu/blob/484b6f77f5b26711688df1b48a71a9528b12f23a/action.yml#L44-L55

In a successful action(in the action session url) you can see output like this when `mermaid` is installed:
```
  npm install @mermaid-js/mermaid-cli@8.8.4
  sudo apt-get install pandoc
  sudo apt-get install graphviz
  pip3 install setuptools wheel
  pip3 install -r /home/runner/work/_actions/drmingdrmer/md2zhihu/ci/requirements.txt
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_USERNAME: drmingdrmer
    GITHUB_TOKEN: ***
```

Before seeing the action output, I can not tell what's going on.
An updated dependency may cause such an issue.

**Comment by drmingdrmer** [comment]
Let me try with the latest version to see if it still works 🤔

**Comment by noneback** [comment]
> Is there a session url for this exception? I need to investigate the environment to figure out what's going on. E.g. url like this: https://github.com/drmingdrmer/drmingdrmer.github.io/runs/5168132554?check_suite_focus=true
> 
> `mmdc` is the `mermaid` binary executable. In the action definition file, it should be installed at line-50:
> 
> https://github.com/drmingdrmer/md2zhihu/blob/484b6f77f5b26711688df1b48a71a9528b12f23a/action.yml#L44-L55
> 
> In a successful action(in the action session url) you can see output like this when `mermaid` is installed:
> 
> ```
>   npm install @mermaid-js/mermaid-cli@8.8.4
>   sudo apt-get install pandoc
>   sudo apt-get install graphviz
>   pip3 install setuptools wheel
>   pip3 install -r /home/runner/work/_actions/drmingdrmer/md2zhihu/ci/requirements.txt
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>   env:
>     GITHUB_USERNAME: drmingdrmer
>     GITHUB_TOKEN: ***
> npm WARN deprecated puppeteer@5.5.0: Version no longer supported. Upgrade to @latest
> 
> added 65 packages, and audited 66 packages in 9s
> 
> 10 packages are looking for funding
>   run `npm fund` for details
> ```
> 
> Before seeing the action output, I can not tell what's going on. An updated dependency may cause such an issue.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6efffa611f56ec72d82904e09542ce6cec2475f017349b5ee2bbdd7954b81165/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f383163656662633439306630393239393032393434666431373537616661333132313737336335376432326233393064343831663731613762376261353934302f64726d696e6764726d65722f64726d696e6764726d65722e6769746875622e696f"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[A  database-concurrency-control.md · drmingdrmer/drmingdrmer.github.io@137cba0](https://github.com/drmingdrmer/drmingdrmer.github.io)**my home. Contribute to drmingdrmer/drmingdrmer.github.io development by creating an account on GitHub.

Thx. Here is my error [session URL](https://github.com/noneback/blog/runs/5788034895?check_suite_focus=true)

**Comment by drmingdrmer** [comment]
I tried with my own blog. Failed too 🤔 .

Working on it!

**Comment by drmingdrmer** [comment]
It seems like `npm bin` is no longer in the `$PATH`:


```
    - name: install deps
      shell: bash
      run: |
        npm bin
        echo $PATH

/home/runner/node_modules/.bin
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I do not know what's changed recently on github workflow.
But adding the bin path into env PATH should fix this issue.

**Comment by drmingdrmer** [comment]
The latest main branch( 80bf939023f1716f54157048571fabb3d0a897bf ) should have fixed this issue.

Feel free to re-opening there is still a failure. :DDD

And thank you so much for letting me know of this issue:DDD
