### ISSUE TITLE
路径不存在 FileNotFoundError "_posts/*.markdown"

### ISSUE THREAD

**Issue by ameaninglessname** [drmingdrmer/md2zhihu#30]
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/runner/work/test.github.io/md2zhihu/__main__.py", line 6, in <module>
>     main()
>   File "/home/runner/work/test.github.io/md2zhihu/md2zhihu/__init__.py", line 974, in main
>     with open(path, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '_posts/*.markdown'

您好,我在使用github action的时候遇到了这个报错

**Comment by drmingdrmer** [comment]
提供下你的项目, 目录结构, 和action配置

**Comment by ameaninglessname** [comment]
> 提供下你的项目, 目录结构, 和action配置

https://github.com/RemRemRemRe/RemRemRemRe.github.io/blob/main/.github/workflows/md2zhihu.yml

**Comment by drmingdrmer** [comment]
`    - uses: drmingdrmer/md2zhihu@v0.5`
这个版本很老了, 用@main试试吧.

**Comment by ameaninglessname** [comment]
> ` - uses: drmingdrmer/md2zhihu@v0.5` 这个版本很老了, 用@main试试吧.

https://github.com/RemRemRemRe/RemRemRemRe.github.io/actions/runs/6847979727/job/18617261328
还是失败了

**Comment by drmingdrmer** [comment]
看起来你的_posts目录里没有`.markdown`结束的文件名会导致`*.markdown`不会被展开,当做普通文件名处理了. 你可以去掉`*.markdown`来让他正常运行, 我这边修改下代码把不存在的文件忽略掉.

**Comment by ameaninglessname** [comment]
> 看起来你的_posts目录里没有`.markdown`结束的文件名会导致`*.markdown`不会被展开,当做普通文件名处理了. 你可以去掉`*.markdown`来让他正常运行, 我这边修改下代码把不存在的文件忽略掉.

谢谢大佬，在去掉之后，以及在workflow file中加上

```yml
permissions:
  contents: write
```
之后，就可以正常工作了。

不过有个问题，子目录中的文档没有生成，应该是没有对目录进行递归处理

**Comment by drmingdrmer** [comment]
> 谢谢大佬，在去掉之后，以及在workflow file中加上
> 
> ```yaml
> permissions:
>   contents: write
> ```

还可以这样啊. 我一直都是在setting里面配置的

**Comment by ameaninglessname** [comment]
> > 子目录中的文档没有生成，应该是没有对目录进行递归处理
> 
> 这些`*.md`的路径是shell展开的, `ls $(find foo -name "*.md")` 可以用来列出更多文件

[我参考了这个文档,使用`_posts/**/*.md`来匹配目录下的所有`.md`后缀的文件了](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths)

**Comment by ameaninglessname** [comment]
不过我发现,生成前后的文本没有任何差异,是现在知乎兼容了md格式了么,还是我没用到一些不兼容的语法

**Comment by drmingdrmer** [comment]
应该还是会有点差异的啊...

**Comment by ameaninglessname** [comment]
> 应该还是会有点差异的啊...

我的,我刚刚找错目录了,是有差异的.

不过我又发现了另一个问题🤣:
目录结构没有被还原,导致子目录下的同名文件,会覆盖掉父级目录中的文件.

> _posts/A.md
> _posts/path/A.md

**Comment by drmingdrmer** [comment]
是的...不支持子目录, 它只输出到同一个输出目录.
