### ISSUE TITLE
zsh: command not found: md2zhihu

### ISSUE THREAD

**Issue by Fangkang515** [drmingdrmer/md2zhihu#8]
# For rendering table to html
brew install pandoc imagemagick node
npm install -g @mermaid-js/mermaid-cli
pip install md2zhihu

感谢作者贡献；

我使用上述命令安装完成后，执行md的转化时，出现：“zsh: command not found: md2zhihu” 错误；

使用的电脑是mac pro，解释器是zsh。

除了”md2zhihu“终端进行md文件转化外，还有别的方式？

期待您的建议~

**Comment by drmingdrmer** [comment]
看下这几个命令是否正常, 如果还有问题贴下这几个命令的输出来看看撒:

- `pip install --verbose md2zhihu` 安装时应该会提示按照成功的字样.
- `which md2zhihu` 如果能到应该会输出它的路径, 例如我的是安装在: `/Users/drdrxp/xp/py3virtual/p38/bin/md2zhihu`
- `echo $PATH` 确认安装的路径在PATH环境变量中: `...:/Users/drdrxp/xp/py3virtual/p38/bin:...`


`md2zhihu`也提供在github action中使用, 本地就不用安装任何东西了, 配置之后每次push会在github里执行, 然后把结果推送到另一个分支: https://github.com/drmingdrmer/md2zhihu/blob/main/README-cn.md#%E4%BD%BF%E7%94%A8-github-action-%E8%BF%9C%E7%A8%8B%E8%BD%AC%E6%8D%A2-%E9%80%82%E5%90%88-windows-%E7%94%A8%E6%88%B7

然后fetch到本地merge这个分支.
